apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
spec:
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-01-01T00:00:00Z"
