# VPS Inventory
# Points to actual VPS servers deployed via Terraform

all:
  children:
    production:
      hosts:
        jterrazz-vps:
          # This will be populated by Terraform output
          # Or manually set your VPS details:
          ansible_host: "{{ hostvars['localhost']['server_ip'] | default('YOUR_VPS_IP') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/hetzner-key
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

          # Optional: host-specific overrides
          # domain_name: "custom-domain.com"  # Override if different from group default
