---
# ArgoCD Application for Default Ingress
# Deploys the landing page and main domain routing

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jterrazz/jterrazz-infra.git
    targetRevision: HEAD
    path: kubernetes/ingress
    directory:
      include: "default-ingress.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
