---
# ArgoCD Application for Portainer
# This will automatically deploy and manage Portainer via GitOps

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jterrazz/jterrazz-infra.git
    targetRevision: HEAD
    path: kubernetes/applications
    directory:
      include: "portainer.yml"
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: ""
    kind: "PersistentVolumeClaim"
    jsonPointers:
    - /spec/volumeName
