---
all:
  children:
    jterrazz:
      hosts:
        jterrazz-multipass:
          ansible_host: 192.168.64.14
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/jterrazz/Developer/jterrazz-infra/local-data/ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

          # Environment configuration
          environment_type: "multipass"

          # Skip components that don't work well in VMs
          skip_security: false  # Enable full security testing
          skip_tailscale: true  # Skip VPN for local testing
          skip_argocd: false    # Enable ArgoCD

      vars:
        ansible_python_interpreter: /usr/bin/python3
