# Static inventory template (NOT USED - kept for reference)
#
# This repository uses DYNAMIC INVENTORY via inventory.py
# The dynamic script automatically discovers VM IP addresses from multipass
#
# Usage: ansible-playbook -i inventories/multipass/inventory.py site.yml

---
# Example static structure (replaced by dynamic inventory.py):
# all:
#   children:
#     jterrazz:
#       hosts:
#         jterrazz-multipass:
#           ansible_host: <DISCOVERED_FROM_MULTIPASS>
#           ansible_user: ubuntu
#           ansible_ssh_private_key_file: /path/to/local-data/ssh/id_rsa
#           environment_type: "multipass"
#       vars:
#         ansible_python_interpreter: /usr/bin/python3
