---
# Global HTTPS redirect middleware
# Used by both local development and production
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-global
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
