---
# Helm installation tasks

- name: Check if Helm is already installed
  ansible.builtin.stat:
    path: "{{ helm_install_dir }}/helm"
  register: helm_binary

- name: Get installed Helm version
  ansible.builtin.command: "{{ helm_install_dir }}/helm version --short"
  register: helm_installed_version
  changed_when: false
  failed_when: false
  when: helm_binary.stat.exists

- name: Download and install Helm
  ansible.builtin.unarchive:
    src: "{{ helm_download_url }}"
    dest: /tmp
    remote_src: true
    creates: "/tmp/linux-{{ helm_arch }}/helm"
  when: not helm_binary.stat.exists or helm_version not in helm_installed_version.stdout | default('')

- name: Copy Helm binary to install directory
  ansible.builtin.copy:
    src: "/tmp/linux-{{ helm_arch }}/helm"
    dest: "{{ helm_install_dir }}/helm"
    mode: '0755'
    remote_src: true
  when: not helm_binary.stat.exists or helm_version not in helm_installed_version.stdout | default('')

- name: Verify Helm installation
  ansible.builtin.command: "{{ helm_install_dir }}/helm version --short"
  register: helm_version_check
  changed_when: false

- name: Add stable Helm repository
  kubernetes.core.helm_repository:
    name: stable
    repo_url: https://charts.helm.sh/stable
    state: present
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Add bitnami Helm repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
    state: present
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Update Helm repositories
  ansible.builtin.command: "{{ helm_install_dir }}/helm repo update"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  changed_when: false

- name: Display Helm installation info
  ansible.builtin.debug:
    msg: |
      ✅ Helm installed successfully!
      • Version: {{ helm_version_check.stdout }}
      • Location: {{ helm_install_dir }}/helm
      • Repositories: stable, bitnami

- name: Clean up download files
  ansible.builtin.file:
    path: "/tmp/linux-{{ helm_arch }}"
    state: absent
