# JTerrazz Infrastructure - Ansible Inventory
# Generated by Terraform

[k3s_cluster]
${server_ip} ansible_host=${server_ip} ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

[k3s_cluster:vars]
domain_name=${domain_name}
environment=${environment}
k3s_version=v1.28.5+k3s1
k3s_token={{ vault_k3s_token | default('your-secure-token-here') }}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
