# Jterrazz Infrastructure - Ansible Inventory
# Generated by Terraform

[production]
${server_ip} ansible_host=${server_ip} ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

[production:vars]
domain_name=${domain_name}
# Note: Most configuration is now in group_vars/production/main.yml
