{{- if .Values.host }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "service.name" . }}-tls
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  secretName: {{ include "service.name" . }}-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - {{ include "service.host" . }}
{{- end }}
