# Production Environment Configuration
# Used for live VPS/cloud deployments

---
# Environment identification
environment_type: "production"
deployment_method: "terraform"
is_production_environment: true

# Security settings (strict for production)
security_level: "production"

# Component configuration for production
skip_security: false # Enable full security hardening
skip_tailscale: false # Enable Tailscale for secure access

# Production TLS settings (handled by cert-manager in Kubernetes)
ssl_provider: "letsencrypt"

# k3s configuration for production
k3s_server: true
k3s_disable_network_policy: false

# Production features
use_cloud_storage: true
use_external_dns: true

# Domain configuration (set via vault or inventory)
# domain_name: "{{ vault_domain_name | default('example.com') }}"

# Tailscale configuration
# tailscale_auth_key: "{{ vault_tailscale_auth_key }}"

# Production logging (minimal verbosity)
production_logging: true
