---
# Tailscale role handlers

- name: Restart tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted
    daemon_reload: true
  listen: "restart tailscaled"

- name: Reload tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: reloaded
    daemon_reload: true
  listen: "reload tailscaled"
