#!/bin/bash
# Deploy Kubernetes applications after Ansible setup
# This script applies all the kubernetes/ manifests

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Helper functions
info() { echo -e "${BLUE}ℹ️ $1${NC}"; }
success() { echo -e "${GREEN}✅ $1${NC}"; }
warning() { echo -e "${YELLOW}⚠️ $1${NC}"; }
error() { echo -e "${RED}❌ $1${NC}"; }

# Check if kubectl is available and cluster is reachable
check_cluster() {
    info "Checking cluster connectivity..."
    
    if ! command -v kubectl &> /dev/null; then
        error "kubectl not found. Please install kubectl or use the kubeconfig from the VM."
        exit 1
    fi
    
    # Set kubeconfig if local file exists and KUBECONFIG is not set
    if [[ -z "${KUBECONFIG:-}" ]] && [[ -f "local-kubeconfig.yaml" ]]; then
        info "Using local kubeconfig file..."
        export KUBECONFIG="$(pwd)/local-kubeconfig.yaml"
    fi
    
    if ! kubectl cluster-info &> /dev/null; then
        error "Cannot connect to Kubernetes cluster. Please check your kubeconfig."
        info "Hint: Run 'make kubeconfig' to get the kubeconfig from your VM."
        if [[ -f "local-kubeconfig.yaml" ]]; then
            info "Or set: export KUBECONFIG=$(pwd)/local-kubeconfig.yaml"
        fi
        exit 1
    fi
    
    success "Connected to cluster"
}

# Deploy Traefik middleware configurations
deploy_traefik_configs() {
    info "Deploying Traefik middleware configurations..."
    
    if kubectl apply -f kubernetes/traefik/middleware.yml; then
        success "Traefik middleware deployed"
    else
        warning "Failed to deploy Traefik middleware (may already exist)"
    fi
}

# Deploy ArgoCD applications for GitOps
deploy_argocd_apps() {
    info "Deploying ArgoCD applications for GitOps automation..."
    
    # Deploy the ArgoCD applications that will manage everything else
    for app in kubernetes/argocd/*.yml; do
        if [[ -f "$app" ]]; then
            info "Deploying ArgoCD app: $(basename "$app")"
            if kubectl apply -f "$app"; then
                success "Applied $(basename "$app")"
            else
                warning "Failed to apply $(basename "$app")"
            fi
        fi
    done
    
    info "ArgoCD will now automatically sync and deploy your applications!"
    info "Check status at: kubectl get applications -n argocd"
}

# Wait for ArgoCD to sync applications
wait_for_sync() {
    info "Waiting for ArgoCD to sync applications..."
    
    # Give ArgoCD some time to detect and sync the applications
    sleep 10
    
    info "Checking ArgoCD application status..."
    kubectl get applications -n argocd || true
    
    success "ArgoCD applications are now managing your infrastructure!"
    info "Visit ArgoCD dashboard to monitor deployments."
}

# Display access information
show_access_info() {
    success "🚀 Deployment Complete!"
    echo
    info "Access your applications:"
    echo "  • ArgoCD: kubectl port-forward -n argocd svc/argocd-server 8080:443"
    echo "  • Portainer: kubectl port-forward -n portainer svc/portainer 9000:9000"
    echo "  • Traefik Dashboard: kubectl port-forward -n kube-system svc/traefik 8081:9000"
    echo
    info "Or access via ingress (if domain is configured):"
    echo "  • ArgoCD: https://argocd.yourdomain.com"
    echo "  • Portainer: https://portainer.yourdomain.com"
    echo "  • Landing Page: https://yourdomain.com"
    echo
    warning "Note: SSL certificates will be automatically generated by Traefik ACME"
}

# Main execution
main() {
    echo -e "${GREEN}🚀 Deploying Kubernetes Applications${NC}"
    echo "This will deploy your applications via ArgoCD GitOps"
    echo
    
    check_cluster
    deploy_traefik_configs
    deploy_argocd_apps
    wait_for_sync
    show_access_info
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
