---
# Simple Landing Page for Local Development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-landing
  namespace: default
  labels:
    app: nginx-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-landing
  template:
    metadata:
      labels:
        app: nginx-landing
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        volumeMounts:
        - name: landing-page-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: landing-page-content
        configMap:
          name: default-landing-page

---
# Service for Landing Page
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    app: nginx-landing
spec:
  selector:
    app: nginx-landing
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
