---
# k3s role handlers

- name: Restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    daemon_reload: true
  listen: "restart k3s"

- name: Reload k3s
  ansible.builtin.systemd:
    name: k3s
    state: reloaded
    daemon_reload: true
  listen: "reload k3s"
